import { FormConfig, InputConfig, PageConfig } from "../types";
import { NameUtils } from "../utils/NameUtils";

/**
 * PythonApiBuilder
 * ─────────────────────────────────────────────────────────────────────────────
 * Generates a complete, standalone FastAPI Python file from a FormConfig.
 *
 * The generated file provides:
 *   GET  /              →  form metadata (title, page count)
 *   GET  /schema        →  full form schema (all pages + fields)
 *   GET  /pages         →  array of page schemas
 *   GET  /pages/{index} →  single page schema by zero-based index
 *   POST /submit        →  validates and echoes a full form submission
 *   POST /submit/{index}→  validates and echoes a single-page submission
 *
 * Open http://localhost:8000/docs in a browser for the interactive
 * Swagger UI — all responses are JSON.
 *
 * Run with:  pip install fastapi uvicorn[standard] pydantic[email]
 *            python api.py
 */
export class PythonApiBuilder {
  /**
   * Generates the full Python source file as a string.
   * @param config  A validated FormConfig object.
   */
  build(config: FormConfig): string {
    const title       = this._escPy(config.formTitle);
    const pageCount   = config.pages.length;
    const needsEmail  = config.pages.some(p => p.inputs.some(i => i.type === "email"));
    const needsUrl    = config.pages.some(p => p.inputs.some(i => i.type === "url"));

    const models      = config.pages.map((p, i) => this._buildPageModel(p, i)).join("\n\n");
    const fullModel   = this._buildFullModel(config.pages);
    const schemaData  = this._buildSchemaData(config);
    const routes      = this._buildRoutes(config.pages, title, pageCount);

    return [
      this._header(title),
      this._imports(needsEmail, needsUrl),
      "",
      this._appInit(title, pageCount),
      "",
      "# ── Pydantic Models (one per form page) ─────────────────────────────────────",
      models,
      "",
      "# ── Full-submission model (all pages combined) ───────────────────────────────",
      fullModel,
      "",
      "# ── Static schema data (mirrors form-config.json) ───────────────────────────",
      schemaData,
      "",
      "# ── Routes ───────────────────────────────────────────────────────────────────",
      routes,
      "",
      this._entryPoint(),
    ].join("\n");
  }

  // ── Private: top-level sections ───────────────────────────────────────────

  private _header(title: string): string {
    return `# ============================================================
# Generated by Form_Man
# Form  : ${title}
# Run   : python api.py
# Docs  : http://localhost:8000/docs   (Swagger UI - JSON in browser)
# ReDoc : http://localhost:8000/redoc
# ============================================================`;
  }

  private _imports(needsEmail: boolean, needsUrl: boolean): string {
    const typingImports = ["Any", "Dict", "List", "Optional"];
    const pydanticImports = ["BaseModel", "Field"];
    if (needsEmail) pydanticImports.push("EmailStr");
    if (needsUrl)   pydanticImports.push("AnyUrl");

    return [
      `from fastapi import FastAPI, HTTPException, Path`,
      `from fastapi.middleware.cors import CORSMiddleware`,
      `from pydantic import ${pydanticImports.join(", ")}`,
      `from typing import ${typingImports.join(", ")}`,
      `import uvicorn`,
    ].join("\n");
  }

  private _appInit(title: string, pageCount: number): string {
    return `app = FastAPI(
    title="${title} API",
    description="Auto-generated API for the '${title}' multi-step form. "
                "Use POST /submit to submit the full form, or POST /submit/{{index}} "
                "to submit one page at a time. Open /docs for interactive JSON UI.",
    version="1.0.0",
)

# Allow the generated form.html to call this API from the browser.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

TOTAL_PAGES = ${pageCount}`;
  }

  private _entryPoint(): string {
    return `if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
`;
  }

  // ── Private: Pydantic models ──────────────────────────────────────────────

  /**
   * Builds a Pydantic BaseModel class for one form page.
   */
  private _buildPageModel(page: PageConfig, index: number): string {
    const className = this._toClassName(page.pageTitle);
    const fields    = page.inputs.map(inp => this._buildField(inp)).join("\n");

    return [
      `class ${className}(BaseModel):`,
      `    """Fields for page ${index + 1}: ${page.pageTitle}"""`,
      fields,
    ].join("\n");
  }

  /**
   * Builds a combined Pydantic model that holds one sub-model per page.
   */
  private _buildFullModel(pages: PageConfig[]): string {
    const lines = pages.map((p, i) => {
      const className = this._toClassName(p.pageTitle);
      const fieldName = this._toSnake(p.pageTitle);
      return `    ${fieldName}: ${className} = Field(..., description="Page ${i + 1}: ${p.pageTitle}")`;
    });

    return [
      `class FullSubmission(BaseModel):`,
      `    """Complete submission containing all form pages."""`,
      ...lines,
    ].join("\n");
  }

  /**
   * Builds one Pydantic field line for an input.
   */
  private _buildField(input: InputConfig): string {
    const name        = this._toSnake(input.name);
    const pyType      = this._toPyType(input.type);
    const isRequired  = input.required === true;
    const fieldArgs   = this._buildFieldArgs(input);

    if (isRequired) {
      return `    ${name}: ${pyType} = Field(${fieldArgs})`;
    } else {
      return `    ${name}: Optional[${pyType}] = Field(None${fieldArgs ? ", " + fieldArgs : ""})`;
    }
  }

  /**
   * Builds the Field(...) arguments for an input.
   */
  private _buildFieldArgs(input: InputConfig): string {
    const args: string[] = [];

    if (input.required) args.push("...");

    if (input.type === "number") {
      args.push(`le=${input.limit}`);
      args.push(`description="Max value: ${input.limit}"`);
    } else if (input.type !== "url" && input.type !== "email") {
      args.push(`max_length=${input.limit}`);
      args.push(`description="Max ${input.limit} characters"`);
    } else {
      args.push(`description="${input.name}"`);
    }

    return args.join(", ");
  }

  // ── Private: schema data ──────────────────────────────────────────────────

  /**
   * Builds a Python dict literal that mirrors the full form schema.
   * Embedded as a constant so GET /schema and GET /pages never need to
   * re-derive the structure at runtime.
   */
  private _buildSchemaData(config: FormConfig): string {
    const pagesLiteral = config.pages.map((page, pi) => {
      const inputsLiteral = page.inputs.map(inp => {
        return [
          `            {`,
          `                "name": "${this._escPy(inp.name)}",`,
          `                "field": "${this._toSnake(inp.name)}",`,
          `                "type": "${inp.type}",`,
          `                "limit": ${inp.limit},`,
          `                "required": ${inp.required ? "True" : "False"},`,
          `                "placeholder": "${this._escPy(inp.placeholder ?? inp.name)}",`,
          `            }`,
        ].join("\n");
      }).join(",\n");

      return [
        `        {`,
        `            "index": ${pi},`,
        `            "pageTitle": "${this._escPy(page.pageTitle)}",`,
        `            "model": "${this._toClassName(page.pageTitle)}",`,
        `            "inputs": [`,
        inputsLiteral,
        `            ],`,
        `        }`,
      ].join("\n");
    }).join(",\n");

    return [
      `FORM_SCHEMA: Dict[str, Any] = {`,
      `    "formTitle": "${this._escPy(config.formTitle)}",`,
      `    "transition": "${config.transition ?? "slide"}",`,
      `    "transitionDuration": "${config.transitionDuration ?? "0.4s"}",`,
      `    "transitionDelay": "${config.transitionDelay ?? "0s"}",`,
      `    "pages": [`,
      pagesLiteral,
      `    ],`,
      `}`,
    ].join("\n");
  }

  // ── Private: routes ───────────────────────────────────────────────────────

  private _buildRoutes(pages: PageConfig[], title: string, pageCount: number): string {
    const pageRoutes = pages.map((p, i) => this._buildPageRoutes(p, i)).join("\n\n");

    return [
      this._buildRootRoute(title, pageCount),
      "",
      this._buildSchemaRoute(),
      "",
      this._buildPagesListRoute(),
      "",
      this._buildPageByIndexRoute(pages),
      "",
      this._buildFullSubmitRoute(),
      "",
      pageRoutes,
    ].join("\n");
  }

  private _buildRootRoute(title: string, pageCount: number): string {
    return `@app.get("/", summary="Form metadata")
def get_root() -> Dict[str, Any]:
    """Returns high-level metadata about the form."""
    return {
        "title": "${this._escPy(title)}",
        "totalPages": ${pageCount},
        "docs": "/docs",
        "schema": "/schema",
        "pages": "/pages",
        "submit": "/submit",
    }`;
  }

  private _buildSchemaRoute(): string {
    return `@app.get("/schema", summary="Full form schema")
def get_schema() -> Dict[str, Any]:
    """Returns the complete form schema — all pages and all fields."""
    return FORM_SCHEMA`;
  }

  private _buildPagesListRoute(): string {
    return `@app.get("/pages", summary="All page schemas")
def get_pages() -> List[Dict[str, Any]]:
    """Returns a list of every page's schema (title + fields)."""
    return FORM_SCHEMA["pages"]`;
  }

  private _buildPageByIndexRoute(pages: PageConfig[]): string {
    const lastIndex = pages.length - 1;
    return `@app.get("/pages/{index}", summary="Single page schema")
def get_page(
    index: int = Path(..., ge=0, le=${lastIndex}, description="Zero-based page index (0 to ${lastIndex})")
) -> Dict[str, Any]:
    """Returns the schema for one page by its zero-based index."""
    return FORM_SCHEMA["pages"][index]`;
  }

  private _buildFullSubmitRoute(): string {
    return `@app.post("/submit", summary="Submit the full form")
def submit_full(data: FullSubmission) -> Dict[str, Any]:
    """
    Accepts a complete form submission (all pages).
    Pydantic validates every field automatically — invalid data returns HTTP 422.
    """
    return {
        "status": "ok",
        "message": "Full form submitted successfully.",
        "data": data.model_dump(),
    }`;
  }

  private _buildPageRoutes(page: PageConfig, index: number): string {
    const className = this._toClassName(page.pageTitle);
    const slug      = this._toSlug(page.pageTitle);

    return `@app.post("/submit/${index}", summary="Submit page ${index + 1}: ${page.pageTitle}")
def submit_page_${index}(data: ${className}) -> Dict[str, Any]:
    """
    Accepts a submission for page ${index + 1} only: **${page.pageTitle}**.
    Useful for per-page validation in a multi-step flow.
    """
    return {
        "status": "ok",
        "page": ${index},
        "pageTitle": "${this._escPy(page.pageTitle)}",
        "data": data.model_dump(),
    }`;
  }

  // ── Private: name converters (delegated to NameUtils) ────────────────────

  private _toSnake(name: string): string    { return NameUtils.toSnakeCase(name); }
  private _toClassName(name: string): string { return NameUtils.toClassName(name); }
  private _toSlug(name: string): string      { return NameUtils.toSlug(name); }

  /** Map form input types to Python/Pydantic types */
  private _toPyType(type: string): string {
    const map: Record<string, string> = {
      text:     "str",
      email:    "EmailStr",
      number:   "int",
      password: "str",
      url:      "AnyUrl",
      tel:      "str",
      date:     "str",
      textarea: "str",
    };
    return map[type] ?? "str";
  }

  /** Escape single quotes and backslashes for Python string literals */
  private _escPy(val: string): string {
    return val.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  }
}

