# ============================================================
# Generated by Form_Man
# Form  : My Book App Form
# Run   : python api.py
# Docs  : http://localhost:8000/docs   (Swagger UI - JSON in browser)
# ReDoc : http://localhost:8000/redoc
# ============================================================
from fastapi import FastAPI, HTTPException, Path
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, EmailStr, AnyUrl
from typing import Any, Dict, List, Optional
import uvicorn

app = FastAPI(
    title="My Book App Form API",
    description="Auto-generated API for the 'My Book App Form' multi-step form. "
                "Use POST /submit to submit the full form, or POST /submit/{{index}} "
                "to submit one page at a time. Open /docs for interactive JSON UI.",
    version="1.0.0",
)

# Allow the generated form.html to call this API from the browser.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

TOTAL_PAGES = 3

# ── Pydantic Models (one per form page) ─────────────────────────────────────
class PersonalInfo(BaseModel):
    """Fields for page 1: Personal Info"""
    first_name: str = Field(..., max_length=50, description="Max 50 characters")
    last_name: str = Field(..., max_length=50, description="Max 50 characters")
    age: Optional[int] = Field(None, le=120, description="Max value: 120")
    email: EmailStr = Field(..., description="Email")

class BookPreferences(BaseModel):
    """Fields for page 2: Book Preferences"""
    favourite_genre: Optional[str] = Field(None, max_length=40, description="Max 40 characters")
    books_per_year: Optional[int] = Field(None, le=999, description="Max value: 999")
    goodreads_url: Optional[AnyUrl] = Field(None, description="Goodreads URL")

class AccountSetup(BaseModel):
    """Fields for page 3: Account Setup"""
    username: str = Field(..., max_length=20, description="Max 20 characters")
    password: str = Field(..., max_length=64, description="Max 64 characters")

# ── Full-submission model (all pages combined) ───────────────────────────────
class FullSubmission(BaseModel):
    """Complete submission containing all form pages."""
    personal_info: PersonalInfo = Field(..., description="Page 1: Personal Info")
    book_preferences: BookPreferences = Field(..., description="Page 2: Book Preferences")
    account_setup: AccountSetup = Field(..., description="Page 3: Account Setup")

# ── Static schema data (mirrors form-config.json) ───────────────────────────
FORM_SCHEMA: Dict[str, Any] = {
    "formTitle": "My Book App Form",
    "transition": "zoom",
    "transitionDuration": "0.4s",
    "transitionDelay": "0s",
    "pages": [
        {
            "index": 0,
            "pageTitle": "Personal Info",
            "model": "PersonalInfo",
            "inputs": [
            {
                "name": "First Name",
                "field": "first_name",
                "type": "text",
                "limit": 50,
                "required": True,
                "placeholder": "First Name",
            },
            {
                "name": "Last Name",
                "field": "last_name",
                "type": "text",
                "limit": 50,
                "required": True,
                "placeholder": "Last Name",
            },
            {
                "name": "Age",
                "field": "age",
                "type": "number",
                "limit": 120,
                "required": False,
                "placeholder": "Age",
            },
            {
                "name": "Email",
                "field": "email",
                "type": "email",
                "limit": 100,
                "required": True,
                "placeholder": "Email",
            }
            ],
        },
        {
            "index": 1,
            "pageTitle": "Book Preferences",
            "model": "BookPreferences",
            "inputs": [
            {
                "name": "Favourite Genre",
                "field": "favourite_genre",
                "type": "text",
                "limit": 40,
                "required": False,
                "placeholder": "Favourite Genre",
            },
            {
                "name": "Books Per Year",
                "field": "books_per_year",
                "type": "number",
                "limit": 999,
                "required": False,
                "placeholder": "Books Per Year",
            },
            {
                "name": "Goodreads URL",
                "field": "goodreads_url",
                "type": "url",
                "limit": 200,
                "required": False,
                "placeholder": "Goodreads URL",
            }
            ],
        },
        {
            "index": 2,
            "pageTitle": "Account Setup",
            "model": "AccountSetup",
            "inputs": [
            {
                "name": "Username",
                "field": "username",
                "type": "text",
                "limit": 20,
                "required": True,
                "placeholder": "Username",
            },
            {
                "name": "Password",
                "field": "password",
                "type": "password",
                "limit": 64,
                "required": True,
                "placeholder": "Password",
            }
            ],
        }
    ],
}

# ── Routes ───────────────────────────────────────────────────────────────────
@app.get("/", summary="Form metadata")
def get_root() -> Dict[str, Any]:
    """Returns high-level metadata about the form."""
    return {
        "title": "My Book App Form",
        "totalPages": 3,
        "docs": "/docs",
        "schema": "/schema",
        "pages": "/pages",
        "submit": "/submit",
    }

@app.get("/schema", summary="Full form schema")
def get_schema() -> Dict[str, Any]:
    """Returns the complete form schema — all pages and all fields."""
    return FORM_SCHEMA

@app.get("/pages", summary="All page schemas")
def get_pages() -> List[Dict[str, Any]]:
    """Returns a list of every page's schema (title + fields)."""
    return FORM_SCHEMA["pages"]

@app.get("/pages/{index}", summary="Single page schema")
def get_page(
    index: int = Path(..., ge=0, le=2, description="Zero-based page index (0 to 2)")
) -> Dict[str, Any]:
    """Returns the schema for one page by its zero-based index."""
    return FORM_SCHEMA["pages"][index]

@app.post("/submit", summary="Submit the full form")
def submit_full(data: FullSubmission) -> Dict[str, Any]:
    """
    Accepts a complete form submission (all pages).
    Pydantic validates every field automatically — invalid data returns HTTP 422.
    """
    return {
        "status": "ok",
        "message": "Full form submitted successfully.",
        "data": data.model_dump(),
    }

@app.post("/submit/0", summary="Submit page 1: Personal Info")
def submit_page_0(data: PersonalInfo) -> Dict[str, Any]:
    """
    Accepts a submission for page 1 only: **Personal Info**.
    Useful for per-page validation in a multi-step flow.
    """
    return {
        "status": "ok",
        "page": 0,
        "pageTitle": "Personal Info",
        "data": data.model_dump(),
    }

@app.post("/submit/1", summary="Submit page 2: Book Preferences")
def submit_page_1(data: BookPreferences) -> Dict[str, Any]:
    """
    Accepts a submission for page 2 only: **Book Preferences**.
    Useful for per-page validation in a multi-step flow.
    """
    return {
        "status": "ok",
        "page": 1,
        "pageTitle": "Book Preferences",
        "data": data.model_dump(),
    }

@app.post("/submit/2", summary="Submit page 3: Account Setup")
def submit_page_2(data: AccountSetup) -> Dict[str, Any]:
    """
    Accepts a submission for page 3 only: **Account Setup**.
    Useful for per-page validation in a multi-step flow.
    """
    return {
        "status": "ok",
        "page": 2,
        "pageTitle": "Account Setup",
        "data": data.model_dump(),
    }

if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
